AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  OpenAIApiKey:
    Type: String
    NoEcho: true

Resources:
  LayerForServerlessEmbedAi:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layer/
      CompatibleRuntimes:
        - python3.13

  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatHistoryTable
      Layers:
        - !Ref LayerForServerlessEmbedAi

  ChatFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt ChatFunction.Arn
      AuthType: NONE
      InvokeMode: RESPONSE_STREAM

  ChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: serverless_embed_ai_chat_history
      AttributeDefinitions:
        - AttributeName: browser_id
          AttributeType: S
      KeySchema:
        - AttributeName: browser_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  LambdaUrl:
    Description: "Lambda Function URL endpoint"
    Value: !Sub "https://${ChatFunctionUrl}"