AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiId:
    Type: String
    Description: "Existing HTTP API Gateway ID"
  ApiRegion:
    Type: String
    Description: "API Gateway Region"
  OpenAIApiKey:
    Type: String
    NoEcho: true

Resources:
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.handler
      Runtime: python3.13
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatHistoryTable
      Events:
        ChatAPI:
          Type: Api
          Properties:
            Path: /chat
            Method: post
            # RestApiId: !Ref ApiId # ローカルテスト時はコメントアウト

  ChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: test_chat_history
      AttributeDefinitions:
        - AttributeName: browser_id
          AttributeType: S
      KeySchema:
        - AttributeName: browser_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiId}.execute-api.${ApiRegion}.amazonaws.com/Prod/chat/" 